name: Code Coverage

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  basic-job:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: "3.11" 
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip setuptools wheel
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
        # Install coverage packages
        python -m pip install coverage pytest-cov
    - name: Run tests with coverage
      run: |
        pytest --cov=. --cov-report=xml --ignore=procedural/inflammation/tests --ignore=testing/tests
        cat coverage.xml    
    - name: Upload coverage reports to Codecov
      uses: codecov/codecov-action@v5
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        fail_ci_if_error: true
        files: coverage.xml