name: OS versions

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:

    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    
    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"  # Fixed Python version
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip setuptools wheel
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
        # Install common testing/linting packages
        python -m pip install flake8 pytest
      shell: bash  # Ensures bash commands work on Windows
    - name: Lint with flake8
      run: |
        # More lenient linting - only catch serious errors
        flake8 --select=E9,F63,F7,F82 --show-source --statistics
        # Or to see all issues but not fail the build:
        # flake8 --exit-zero 
    - name: Test with pytest
      run: |
        # Skip tests in directories that have import issues